### ISSUE TITLE
 fatal error C1083: 无法打开包括文件: “tkc/utf8.h”

### ISSUE THREAD

**Issue by fanhaining** [zlgopen/awtk-nodejs#2]
npm install报错了,win平台，vs2017,nodejs8.9.4

**Comment by xianjimli** [comment]
awtk和awtk-nodejs需要取到同一个目录(并列）：
```
awtk
awtk-nodejs
```

**Comment by fanhaining** [comment]
![image](https://user-images.githubusercontent.com/17611077/76048348-7d4fa880-5fa0-11ea-8bb9-6897f13a0fac.png)
库已损坏什么鬼？

**Comment by fanhaining** [comment]
升级nodejs版本解决了
