### ISSUE TITLE
麻烦补充d.ts文件

### ISSUE THREAD

**Issue by fanhaining** [zlgopen/awtk-nodejs#3]
不然很难懂各个参数含义。

**Comment by xianjimli** [comment]
可以参考这个文件：https://github.com/zlgopen/awtk-binding/blob/master/tools/code_gen/js/output/awtk.ts

**Comment by fanhaining** [comment]
好多any- -!

**Comment by xianjimli** [comment]
别着急，any 主要是内部用的，主要是两类：

* declare function
* nativeObj : any;

有注释的函数才是你该调用的。

**Comment by fanhaining** [comment]
好的，谢谢.
