### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _tk_strdup【macOS m1 arm64】

### ISSUE THREAD

**Issue by fanzhiri** [zlgopen/awtk-nodejs#8]
在苹果 MacBook Air M1 2020
编译时提示：building for macOS-x86_64 but attempting to link with file built for macOS-arm64
运行demo时报错：dyld: lazy symbol binding failed: Symbol not found: _tk_strdup

fanzhiri@fanzhirideAir awtk-nodejs % **npm run build**       

> awtk-js@1.0.0 build
> node-gyp configure;node-gyp --verbose build

gyp info it worked if it ends with ok
gyp info using node-gyp@8.1.0
gyp info using node@14.15.1 | darwin | x64
gyp info find Python using Python version 3.8.2 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/fanzhiri/GitHub/awtk-nodejs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/fanzhiri/Library/Caches/node-gyp/14.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/fanzhiri/GitHub/awtk-nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/.bin/node-gyp',
gyp verb cli   '--verbose',
gyp verb cli   'build'
gyp verb cli ]
gyp info using node-gyp@8.1.0
gyp info using node@14.15.1 | darwin | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/fanzhiri/Library/Caches/node-gyp/14.15.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ -o Release/obj.target/awtk/src/c/tk_nodejs.o ../src/c/tk_nodejs.cc '-DNODE_GYP_MODULE_NAME=awtk' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DWITH_FS_RES=1' '-DBUILDING_NODE_EXTENSION' -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/include/node -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/src -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/openssl/config -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/openssl/openssl/include -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/uv/include -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/zlib -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/v8/include -I../. -I/Users/fanzhiri/GitHub/awtk -I/Users/fanzhiri/GitHub/awtk/src -I/Users/fanzhiri/GitHub/awtk/3rd -I/Users/fanzhiri/GitHub/awtk/src/ext_widgets -I/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan -I../node_modules/nan  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/awtk/src/c/tk_nodejs.o.d.raw   -c
In file included from ../src/c/tk_nodejs.cc:2:
In file included from /Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan/nan.h:2884:
/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/include/node/v8.h:5265:3: note: 'GetContents' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
In file included from ../src/c/tk_nodejs.cc:123:
In file included from ../src/c/custom.c:2:
../src/c/jsengine.h:24:49: warning: arithmetic on a null pointer treated as a cast from integer to pointer is a GNU extension [-Wnull-pointer-arithmetic]
  return (int64_t)(v.As<v8::Number>()->Value()) + (char*)NULL;
                                                ^ ~~~~~~~~~~~
In file included from ../src/c/tk_nodejs.cc:123:
../src/c/custom.c:20:38: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Value> jret = Nan::MakeCallback(
                                     ^
/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
3 warnings generated.
  cc -o Release/obj.target/awtk/src/assets.o ../src/assets.c '-DNODE_GYP_MODULE_NAME=awtk' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DWITH_FS_RES=1' '-DBUILDING_NODE_EXTENSION' -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/include/node -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/src -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/openssl/config -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/openssl/openssl/include -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/uv/include -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/zlib -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/v8/include -I../. -I/Users/fanzhiri/GitHub/awtk -I/Users/fanzhiri/GitHub/awtk/src -I/Users/fanzhiri/GitHub/awtk/3rd -I/Users/fanzhiri/GitHub/awtk/src/ext_widgets -I/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan -I../node_modules/nan  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/awtk/src/assets.o.d.raw   -c
  c++ -bundle -undefined dynamic_lookup -Wl,-no_pie -Wl,-search_paths_first -mmacosx-version-min=10.13 -arch x86_64 -L./Release -stdlib=libc++ -L/Users/fanzhiri/GitHub/awtk-nodejs/../awtk/bin -L/Users/fanzhiri/GitHub/awtk-nodejs/../awtk/lib  -o Release/awtk.node Release/obj.target/awtk/src/c/tk_nodejs.o Release/obj.target/awtk/src/assets.o -lawtk_global -lextwidgets -lwidgets -lbase -lconf_io -lubjson -lstreams -lnanovg -lglad -lgpinyin -ltkc_static -lfribidi -llinebreak -lSDL2 -lstdc++ -lpthread -lm -ldl
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libawtk_global.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libextwidgets.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libwidgets.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libbase.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libconf_io.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libubjson.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libstreams.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libnanovg.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libglad.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libgpinyin.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libtkc_static.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libfribidi.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/liblinebreak.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /usr/local/lib/libSDL2.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
gyp info ok 
fanzhiri@fanzhirideAir awtk-nodejs % **node demos/button.js**
dyld: lazy symbol binding failed: Symbol not found: _tk_strdup
  Referenced from: /Users/fanzhiri/GitHub/awtk-nodejs/build/Release/awtk.node
  Expected in: flat namespace

dyld: Symbol not found: _tk_strdup
  Referenced from: /Users/fanzhiri/GitHub/awtk-nodejs/build/Release/awtk.node
  Expected in: flat namespace

zsh: abort      node demos/button.js

**Comment by xianjimli** [comment]
麻烦更新一下awtk-nodejs，重新编译后，如果还有上面的问题，运行下面的命令，看看有没有tk_strdup函数：

```
nm -C build/Release/awtk.node|grep tk_strdup
```

**Comment by fanzhiri** [comment]
> 麻烦更新一下awtk-nodejs，重新编译后，如果还有上面的问题，运行下面的命令，看看有没有tk_strdup函数：
> 
> ```
> nm -C build/Release/awtk.node|grep tk_strdup
> ```

更新后编译还是一样问题，有tk_strdup函数，详见如下过程

`

fanzhiri@fanzhirideAir awtk-nodejs % git pull  
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Updating b0c5999..3767459
Fast-forward
 awtk.d.ts          | 21 +++++++++++++++------
 awtk.js            | 35 +++++++++++++++++++++++------------
 package-lock.json  |  6 +++---
 src/c/tk_nodejs.cc | 39 ++++++++++++++++++++++++++++-----------
 src/js/awtk.d.ts   | 21 +++++++++++++++------
 src/js/awtk.js     | 35 +++++++++++++++++++++++------------
 src/js/awtk.js.map |  2 +-
 7 files changed, 108 insertions(+), 51 deletions(-)
fanzhiri@fanzhirideAir awtk-nodejs % rm -rf build
fanzhiri@fanzhirideAir awtk-nodejs % npm run build

> awtk-js@1.0.0 build
> node-gyp configure;node-gyp --verbose build

gyp info it worked if it ends with ok
gyp info using node-gyp@8.1.0
gyp info using node@14.15.1 | darwin | x64
gyp info find Python using Python version 3.8.2 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/fanzhiri/GitHub/awtk-nodejs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/fanzhiri/Library/Caches/node-gyp/14.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/fanzhiri/GitHub/awtk-nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/.bin/node-gyp',
gyp verb cli   '--verbose',
gyp verb cli   'build'
gyp verb cli ]
gyp info using node-gyp@8.1.0
gyp info using node@14.15.1 | darwin | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/fanzhiri/Library/Caches/node-gyp/14.15.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ -o Release/obj.target/awtk/src/c/tk_nodejs.o ../src/c/tk_nodejs.cc '-DNODE_GYP_MODULE_NAME=awtk' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DWITH_FS_RES=1' '-DBUILDING_NODE_EXTENSION' -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/include/node -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/src -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/openssl/config -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/openssl/openssl/include -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/uv/include -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/zlib -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/v8/include -I../. -I/Users/fanzhiri/GitHub/awtk -I/Users/fanzhiri/GitHub/awtk/src -I/Users/fanzhiri/GitHub/awtk/3rd -I/Users/fanzhiri/GitHub/awtk/src/ext_widgets -I/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan -I../node_modules/nan  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/awtk/src/c/tk_nodejs.o.d.raw   -c
In file included from ../src/c/tk_nodejs.cc:2:
In file included from /Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan/nan.h:2884:
/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/include/node/v8.h:5265:3: note: 'GetContents' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
In file included from ../src/c/tk_nodejs.cc:123:
In file included from ../src/c/custom.c:2:
../src/c/jsengine.h:24:49: warning: arithmetic on a null pointer treated as a cast from integer to pointer is a GNU extension [-Wnull-pointer-arithmetic]
  return (int64_t)(v.As<v8::Number>()->Value()) + (char*)NULL;
                                                ^ ~~~~~~~~~~~
In file included from ../src/c/tk_nodejs.cc:123:
../src/c/custom.c:20:38: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Value> jret = Nan::MakeCallback(
                                     ^
/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan/nan.h:1024:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
3 warnings generated.
  cc -o Release/obj.target/awtk/src/assets.o ../src/assets.c '-DNODE_GYP_MODULE_NAME=awtk' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DWITH_FS_RES=1' '-DBUILDING_NODE_EXTENSION' -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/include/node -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/src -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/openssl/config -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/openssl/openssl/include -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/uv/include -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/zlib -I/Users/fanzhiri/Library/Caches/node-gyp/14.15.1/deps/v8/include -I../. -I/Users/fanzhiri/GitHub/awtk -I/Users/fanzhiri/GitHub/awtk/src -I/Users/fanzhiri/GitHub/awtk/3rd -I/Users/fanzhiri/GitHub/awtk/src/ext_widgets -I/Users/fanzhiri/GitHub/awtk-nodejs/node_modules/nan -I../node_modules/nan  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/awtk/src/assets.o.d.raw   -c
  c++ -bundle -undefined dynamic_lookup -Wl,-no_pie -Wl,-search_paths_first -mmacosx-version-min=10.13 -arch x86_64 -L./Release -stdlib=libc++ -L/Users/fanzhiri/GitHub/awtk-nodejs/../awtk/bin -L/Users/fanzhiri/GitHub/awtk-nodejs/../awtk/lib  -o Release/awtk.node Release/obj.target/awtk/src/c/tk_nodejs.o Release/obj.target/awtk/src/assets.o -lawtk_global -lextwidgets -lwidgets -lbase -lconf_io -lubjson -lstreams -lnanovg -lglad -lgpinyin -ltkc_static -lfribidi -llinebreak -lSDL2 -lstdc++ -lpthread -lm -ldl
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libawtk_global.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libextwidgets.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libwidgets.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libbase.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libconf_io.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libubjson.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libstreams.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libnanovg.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libglad.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libgpinyin.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libtkc_static.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libfribidi.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/liblinebreak.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /usr/local/lib/libSDL2.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
gyp info ok 
fanzhiri@fanzhirideAir awtk-nodejs % node demos/button.js 
dyld: lazy symbol binding failed: Symbol not found: _tk_strdup
  Referenced from: /Users/fanzhiri/GitHub/awtk-nodejs/build/Release/awtk.node
  Expected in: flat namespace

dyld: Symbol not found: _tk_strdup
  Referenced from: /Users/fanzhiri/GitHub/awtk-nodejs/build/Release/awtk.node
  Expected in: flat namespace

zsh: abort      node demos/button.js
fanzhiri@fanzhirideAir awtk-nodejs % nm -C build/Release/awtk.node|grep tk_strdup
                 U _tk_strdup
`

**Comment by xianjimli** [comment]
很奇怪，我这里是有的：
```
jim@lixianjings-MacBook-Pro awtk-nodejs % nm -C build/Release/awtk.node|grep tk_strdup
00000000001f2a50 T _tk_strdup
```

**Comment by fanzhiri** [comment]
> 很奇怪，我这里是有的：
> 
> ```
> jim@lixianjings-MacBook-Pro awtk-nodejs % nm -C build/Release/awtk.node|grep tk_strdup
> 00000000001f2a50 T _tk_strdup
> ```

你的MacBook是intel芯片【x86】，我的是apple m1芯片【arm】

**Comment by xianjimli** [comment]
```
d: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libawtk_global.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```
/Users/fanzhiri/GitHub/awtk/lib/libawtk_global.a 怎么是x86的呢

**Comment by fanzhiri** [comment]
> ```
> d: warning: ignoring file /Users/fanzhiri/GitHub/awtk/lib/libawtk_global.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
> ```
> 
> 
>      
>   
> 
> /Users/fanzhiri/GitHub/awtk/lib/libawtk_global.a 怎么是x86的呢

现在卡住了，怎么继续？你们没有同事用macbook m1 的笔记本吗？

**Comment by xianjimli** [comment]
没有用macbook m1 的同事。你重新编译一下awtk:

先clean：
```
scons -c
```

重新编译，并把前面一段的log贴上来看看。
```
scons
```

**Comment by fanzhiri** [comment]
> 没有用macbook m1 的同事。你重新编译一下awtk:
> 
> 先clean：
> 
> ```
> scons -c
> ```
> 
> 重新编译，并把前面一段的log贴上来看看。
> 
> ```
> scons
> ```

fanzhiri@fanzhirideAir awtk % scons   
scons: Reading SConscript files ...
MACH=arm64 ARCH=('64bit', '') TARGET_ARCH=
TK_ROOT: /Users/fanzhiri/GitHub/awtk
WIN32_AWTK_RES: win32_res/awtk.res
node tools/idl_gen/tkc.js tools/idl_gen/tkc.json

**Comment by xianjimli** [comment]
log再多一点，两三屏吧。

**Comment by fanzhiri** [comment]
> log再多一点，两三屏吧。
我把log放到云盘了
链接: https://pan.baidu.com/s/17-hYEqYWW5M_3vyLjKTdcQ  密码: i7i1

**Comment by xianjimli** [comment]
编译参数看起来没问题啊，难到gcc在m1上默认编译出来是x86的吗？
```
gcc -o src/tkc/str.o -c -g -Wall -Wno-unused-function -fPIC -DWITHOUT_GLAD=1 -DTK_ROOT="\"/Users/fanzhiri/GitHub/awtk\"" -DWITH_MBEDTLS=1 -DENABLE_CURSOR=1 -DWITH_TEXT_BIDI=1 -DWITH_DATA_READER_WRITER=1 -DWITH_EVENT_RECORDER_PLAYER=1 -DWITH_ASSET_LOADER -DWITH_FS_RES -DWITH_ASSET_LOADER_ZIP -DSTBTT_STATIC -DSTB_IMAGE_STATIC -DWITH_STB_IMAGE -DWITH_VGCANVAS -DWITH_UNICODE_BREAK -DWITH_DESKTOP_STYLE -DWITH_SDL -DHAS_STDIO -DHAVE_STDIO_H -DHAS_GET_TIME_US64 -DHAS_STD_MALLOC -DTK_MAX_MEM_BLOCK_NR=3 -DWITH_IME_PINYIN -DWITH_NANOVG_GPU -DWITH_VGCANVAS_LCD -DWITH_STB_FONT -DWITH_NANOVG_GL3 -DWITH_NANOVG_GL -DHAS_SEM_OPEN -D__APPLE__ -DHAS_PTHREAD -DMACOS -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DBGFX_CONFIG_RENDERER_METAL=1 -DWITH_WIDGET_TYPE_CHECK=1 -I. -Isrc -I3rd -Isrc/ext_widgets -Isrc/custom_widgets -I3rd/fribidi -I3rd/mbedtls/include -I3rd/mbedtls/3rdparty/everest/include -I3rd/pixman -I3rd/cairo -I3rd/bgfx/bgfx/include -I3rd/bgfx/bx/include -I3rd/bgfx/bimg/include -I3rd/agge -I3rd/agg/include -I3rd/nanovg -I3rd/nanovg/gl -I3rd/nanovg/base -I3rd/nanovg/agge -I3rd/nanovg/bgfx -I3rd/SDL/src -I3rd/SDL/include -I3rd/agge/src -I3rd/agge/include -I3rd/gpinyin/include -I3rd/libunibreak -I3rd/gtest/googletest -I3rd/gtest/googletest/include -Itools -Ires src/tkc/str.c
```

你运行下面两个命令，把输出贴上来我看看。

```
objdump -h  src/tkc/str_str.o
```

```
objdump -h lib/libtkc_static.a
```

**Comment by fanzhiri** [comment]
> objdump -h  src/tkc/str_str.o

链接: https://pan.baidu.com/s/15o87HTS0HtcH3vEEGMcdvQ  密码: lhhw

**Comment by xianjimli** [comment]
那AWTK没问题。

又看了一下之前的log，可能是node-gyp的问题，这个我也不知道，你到node-gyp那里问一下。

```
gyp info using node-gyp@8.1.0
gyp info using node@14.15.1 | darwin | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/fanzhiri/Library/Caches/node-gyp/14.15.1
```

**Comment by fanzhiri** [comment]
两步走
第一步：执行两命令
echo "export arch=arm64" >> ~/.zsh_profile
source ~./zsh_profile
第二步：改写package.json的scripts的build命令一行，添上--arch=arm64

  "scripts": {
    "rebuild": "node-gyp clean;node-gyp configure;node-gyp --verbose build",
    "config": "node-gyp configure",
     "build": "node-gyp configure ;node-gyp --verbose  build", 改为下面一句
    "build": "node-gyp configure --arch=arm64;node-gyp --verbose --arch=arm64 build",
    "clean": "rm -rf build"
  },
